### ISSUE TITLE
Should we move to master?

### ISSUE THREAD

**Issue by Brown121407** [RoundEnya/MPL#12]
Ce ziceti sa scoatem smartway si sa mutam dumbway pe master? Ca pana la urma pe ala o sa lucram si gata. Si asa apar si contributiile cand mai dam un pr. @RoundEnya/cavalerii-mesei-rotunde

**Comment by BogdanCarp** [comment]
Da , cred ca e ok pentru ca reduce din numarul celor 7 branches din care 4 -5 sunt active. Si oricum putem face Smartwayu , later on , dupa ce facem tot ce se poate folosind kinda 
"simple" stuff
